services:
  auction_svc:
    container_name: auction_svc_name
    build:
      dockerfile: AuctionService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMQ__Host=rabbitmq_name
      - RabbitMQ__Username=guest
      - RabbitMQ__Host=guest
      - IdentityServiceUrl=http://identity_svc_name
      - ConnectionStrings__DefaultConnection=Server=auction_db_name:5432; User Id=postgres;Password=postgrespw;Database=auctions
    ports:
      - 7001:80
  
  search_svc:
    container_name: search_svc_name
    build:
      dockerfile: SearchService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMQ__Host=rabbitmq_name
      - RabbitMQ__Username=guest
      - RabbitMQ__Host=guest
      - ConnectionStrings__MongoDbConnection=mongodb://root:mongopw@search_db_name
      - AuctionServiceUrl=http://auction_svc_name
    ports:
      - 7002:80
  
  auction_db:
    container_name: auction_db_name
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgrespw
    volumes:
      - auction_db:/var/lib/postgresql/data

  search_db:
    container_name: search_db_name
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    volumes:
      - search_db:/var/lib/mongodb/data
  
  rabbitmq:
    container_name: rabbitmq_name
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  auction_db:
  search_db:
  